In [ ]:
import requests
import pandas as pd
import io

url = 'https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_vendas_clientes.json'

try:
    response = requests.get(url)
    response.raise_for_status()
    dados = pd.read_json(io.StringIO(response.text))
    display(dados.head())
except requests.exceptions.RequestException as e:
    print(f"Error fetching the data: {e}")
except ValueError as e:
    print(f"Error parsing JSON data: {e}")

dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [ ]:
dados = pd.json_normalize(dados['dados_vendas'])
dados.head()

Data de venda                                            Cliente  \
0    06/06/2022  [@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...   
1    07/06/2022  [Isabely JOanes 738, Isabely JOanes 738, Isabe...   
2    08/06/2022  [Isabely JOanes 738, JOãO Gabriel 671, Julya m...   
3    09/06/2022  [Julya meireles 914, MaRIA Julia 444, MaRIA Ju...   
4    10/06/2022  [MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...   

                                Valor da compra  
0    [R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]  
1  [R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]  
2  [R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]  
3   [R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]  
4  [R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]

In [ ]:
colunas = list(dados.columns)
colunas

['Data de venda', 'Cliente', 'Valor da compra']

In [ ]:
dados = dados.explode(['Cliente', 'Valor da compra'])
dados.head()

Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31

In [ ]:
dados.reset_index(inplace = True,drop=True)
dados.head()

Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
1    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4    07/06/2022  Isabely JOanes 738       R$ 825,31

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes


In [ ]:
dados['Valor da compra'] = dados['Valor da compra'].apply(lambda x: x.replace('R','').replace('$','').replace(',','').strip())

In [ ]:
import numpy as np

In [ ]:
dados['Valor da compra'] = dados['Valor da compra'].astype(np.float64)
dados.head()

Data de venda             Cliente  Valor da compra
0    06/06/2022     @ANA _LUCIA 321           8365.0
1    06/06/2022  DieGO ARMANDIU 210          57333.0
2    06/06/2022  DieGO ARMANDIU 210           3928.0
3    06/06/2022  DieGO ARMANDIU 210          51234.0
4    07/06/2022  Isabely JOanes 738          82531.0

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Data de venda    20 non-null     object 
 1   Cliente          20 non-null     object 
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes


In [ ]:
dados['Cliente'] = dados['Cliente'].str.lower()

In [ ]:
dados

Data de venda             Cliente  Valor da compra
0     06/06/2022     @ana _lucia 321           8365.0
1     06/06/2022  diego armandiu 210          57333.0
2     06/06/2022  diego armandiu 210           3928.0
3     06/06/2022  diego armandiu 210          51234.0
4     07/06/2022  isabely joanes 738          82531.0
5     07/06/2022  isabely joanes 738          16807.0
6     07/06/2022  isabely joanes 738          33918.0
7     07/06/2022  isabely joanes 738          31469.0
8     08/06/2022  isabely joanes 738          68205.0
9     08/06/2022    joão gabriel 671          38634.0
10    08/06/2022  julya meireles 914          62265.0
11    08/06/2022  julya meireles 914          63079.0
12    09/06/2022  julya meireles 914           3903.0
13    09/06/2022     maria julia 444          75916.0
14    09/06/2022     maria julia 444          33447.0
15    09/06/2022     maria julia 444          67878.0
16    10/06/2022     maria julia 444          31424.0
17    10/06/2022     pedro pasco 812          31115.0
18    10/06/2022    paulo castro 481          89916.0
19    10/06/2022   thiago fritzz 883          88524.0

In [ ]:
dados['Cliente'] = dados['Cliente'].str.replace(r'[^a-z\s]',' ',regex=True)
dados.head()

Data de venda             Cliente  Valor da compra
0    06/06/2022      ana  lucia               8365.0
1    06/06/2022  diego armandiu              57333.0
2    06/06/2022  diego armandiu               3928.0
3    06/06/2022  diego armandiu              51234.0
4    07/06/2022  isabely joanes              82531.0

In [ ]:
dados['Data de venda'] = pd.to_datetime(dados['Data de venda'])
dados.head()

Data de venda             Cliente  Valor da compra
0    2022-06-06      ana  lucia               8365.0
1    2022-06-06  diego armandiu              57333.0
2    2022-06-06  diego armandiu               3928.0
3    2022-06-06  diego armandiu              51234.0
4    2022-07-06  isabely joanes              82531.0

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object        
 2   Valor da compra  20 non-null     float64       
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes


# Objetivo
Criar um subset para visualizar qual foi o cliente que mais comprou no periodo de 5 dias.

## Definir o período de 5 dias

### Subtask:
Determinar as datas de início e fim para o período de 5 dias de interesse.


**Raciocínio**:
Calcular as datas de início e fim para o período de 5 dias com base na coluna 'Data de venda' no dataframe. A data de início será a data mínima e a data de fim será a data mínima mais 4 dias (para incluir a data de início e formar um período de 5 dias).



In [ ]:
data_inicial = dados['Data de venda'].min()
data_final = data_inicial + pd.Timedelta(days=4)
print(f"Data inicial: {data_inicial}")
print(f"Data final: {data_final}")

Data inicial: 2022-06-06 00:00:00
Data final: 2022-06-10 00:00:00


## Filtrar os dados

### Subtask:
Criar um novo DataFrame contendo apenas os dados de vendas dentro do período de 5 dias definido.


**Raciocínio**:
Filtrar o dataframe com base nas datas de início e fim para criar um novo dataframe para o período de 5 dias.






In [ ]:
dados_periodo = dados[(dados['Data de venda'] >= data_inicial) & (dados['Data de venda'] <= data_final)].copy()
dados_periodo.head()

Data de venda             Cliente  Valor da compra
0    2022-06-06      ana  lucia               8365.0
1    2022-06-06  diego armandiu              57333.0
2    2022-06-06  diego armandiu               3928.0
3    2022-06-06  diego armandiu              51234.0

## Agrupar e agregar

### Subtask:
Agrupar os dados filtrados por 'Cliente' e somar o 'Valor da compra' para cada cliente.


**Raciocínio**:
Agrupar os dados filtrados por 'Cliente' e somar o 'Valor da compra' para cada cliente para encontrar o valor total de compra por cliente dentro do período especificado de 5 dias.



In [ ]:
total_compra_por_cliente = dados_periodo.groupby('Cliente')['Valor da compra'].sum()
display(total_compra_por_cliente)

Cliente
 ana  lucia             8365.0
diego armandiu        112495.0
Name: Valor da compra, dtype: float64

## Identificar o cliente com maior compra

### Subtask:
Encontrar o cliente com o maior valor total de compra a partir dos dados agregados.


**Raciocínio**:
Encontrar o cliente com o valor total máximo de compra usando idxmax() e obter o valor total de compra dele.



In [ ]:
cliente_maior_compra = total_compra_por_cliente.idxmax()
valor_maior_compra = total_compra_por_cliente[cliente_maior_compra]
print(f"O cliente que mais comprou no período de 5 dias é: {cliente_maior_compra}")
print(f"O valor total da compra deste cliente é: {valor_maior_compra}")

O cliente que mais comprou no período de 5 dias é: diego armandiu    
O valor total da compra deste cliente é: 112495.0


## Exibir o resultado

### Subtask:
Mostrar o nome do cliente que comprou mais e o valor total de suas compras dentro do período de 5 dias.


**Raciocínio**:
Mostrar o cliente com a maior compra e o valor total de compra dele.



In [ ]:
print(f"O nome do cliente que comprou mais no período de 5 dias é: {cliente_maior_compra}")
print(f"O valor total das compras deste cliente neste período é: {valor_maior_compra}")

O nome do cliente que comprou mais no período de 5 dias é: diego armandiu    
O valor total das compras deste cliente neste período é: 112495.0


## Resumo:

### Principais Descobertas da Análise de Dados

*   O período de 5 dias analisado compreendeu de '2022-06-06 00:00:00' a '2022-06-10 00:00:00'.
*   Dentro deste período, o cliente 'diego armandiu' teve o maior valor total de compra, totalizando 112495.0.
*   Outro cliente, 'ana lucia', também fez compras dentro deste período, totalizando 8365.0.

